const APP_CONSTANTS = {
  DATA: {
    FIRST_TIME_ON_APP: "first_time_on_app",
    SELECTED_DATE: "selected_date",
  },
  NAV: {
    HABITS_HOME: "(habits)",
    SETTINGS: "settings",
    STATS: "stats",
    HABIT_MANAGER: "habitsManager",
  },
  IMAGES: {
    SCENE_1: "/assets/images/header-img-principal-opacity.png",
    SCENE_2: "@/assets/images/scene_1-sky-and-birds.png",
  },
  HABIT: {
    FREQUENCY: {
      DAILY: "daily" as const,
      WEEKLY: "weekly" as const,
      MONTHLY: "monthly" as const,
      YEARLY: "yearly" as const,
      SINGLE: "single" as const,
    },
    GOAL_LABELS: [
      {
        LABEL: "Quantidade" as const,
        VALUE: "units" as const,
      },
      {
        LABEL: "Tempo" as const,
        VALUE: "time" as const,
      },
    ],
    HABIT_ICONS: [
      { key: "1", name: "check-circle", description: "Para marcar tarefas concluídas" },
      { key: "2", name: "alarm", description: "Para definir lembretes de hábitos" },
      { key: "3", name: "fitness-center", description: "Para atividades físicas" },
      { key: "4", name: "restaurant", description: "Para hábitos alimentares saudáveis" },
      { key: "5", name: "bedtime", description: "Para rastrear horários de dormir" },
      { key: "6", name: "water-drop", description: "Para monitorar a ingestão de água" },
      { key: "7", name: "directions-walk", description: "Para caminhadas e passos diários" },
      { key: "8", name: "book", description: "Para leitura diária" },
      { key: "9", name: "self-improvement", description: "Para meditação e mindfulness" },
      { key: "10", name: "brush", description: "Para hábitos de higiene, como escovar os dentes" },
      { key: "11", name: "eco", description: "Para hábitos ecológicos e sustentáveis" },
      { key: "12", name: "health-and-safety", description: "Para hábitos de saúde" },
      {
        key: "13",
        name: "calendar-today",
        description: "Para visualização do calendário de hábitos",
      },
      { key: "14", name: "favorite", description: "Para hábitos favoritos ou mais importantes" },
      { key: "15", name: "sports-basketball", description: "Para atividades esportivas" },
      { key: "16", name: "hiking", description: "Para trilhas e atividades ao ar livre" },
      { key: "17", name: "music-note", description: "Para prática de música ou escutar músicas" },
      {
        key: "18",
        name: "wb-sunny",
        description: "Para hábitos relacionados ao tempo ao ar livre",
      },
      { key: "19", name: "smoke-free", description: "Para monitorar o hábito de não fumar" },
      { key: "20", name: "mood", description: "Para monitorar o humor diário" },
      { key: "21", name: "nature", description: "Para atividades ao ar livre" },
      { key: "22", name: "spa", description: "Para hábitos de relaxamento" },
      { key: "23", name: "fastfood", description: "Para hábitos alimentares" },
      { key: "24", name: "local-drink", description: "Para monitorar consumo de bebidas" },
      { key: "25", name: "directions-bike", description: "Para ciclismo" },
      { key: "26", name: "emoji-people", description: "Para interações sociais" },
      { key: "27", name: "emoji-objects", description: "Para hobbies e interesses" },
      { key: "28", name: "emoji-nature", description: "Para atividades na natureza" },
      {
        key: "29",
        name: "emoji-food-beverage",
        description: "Para hábitos alimentares e de bebida",
      },
      { key: "30", name: "flaky", description: "Para monitorar consistência" },
      { key: "31", name: "fitness-center", description: "Para atividades de ginástica" },
      { key: "32", name: "cleaning-services", description: "Para hábitos de limpeza" },
      { key: "33", name: "psychology", description: "Para monitorar saúde mental" },
      { key: "34", name: "science", description: "Para atividades científicas" },
      { key: "35", name: "sports-soccer", description: "Para atividades esportivas" },
      { key: "36", name: "travel-explore", description: "Para hábitos de viagem e exploração" },
      { key: "37", name: "handyman", description: "Para atividades de bricolagem" },
      { key: "38", name: "biotech", description: "Para monitoramento de saúde" },
      { key: "39", name: "architecture", description: "Para design e planejamento" },
      { key: "40", name: "volunteer-activism", description: "Para voluntariado e ativismo" },
    ],
  },
}

export default APP_CONSTANTS
